"""PyView component ecosystem: layout, content, inputs, data, and status."""

from pyview.components.base import Container
from pyview.components.content import header, json, title, write
from pyview.components.data import (
    CheckboxColumn,
    Column,
    LinkColumn,
    NumberColumn,
    ProgressColumn,
    SelectboxColumn,
    TextColumn,
    data_editor,
    dataframe,
    normalize_tabular_data,
    reconstruct_tabular_data,
    table,
)
from pyview.components.inputs import (
    button,
    chat_input,
    checkbox,
    color_picker,
    date_input,
    download_button,
    feedback,
    file_uploader,
    form_submit_button,
    link_button,
    multiselect,
    number_input,
    pills,
    radio,
    segmented_control,
    select_slider,
    selectbox,
    slider,
    text_area,
    text_input,
    time_input,
    toggle,
)
from pyview.components.layout import (
    CardContainer,
    ColumnContainer,
    ExpanderContainer,
    FormContainer,
    SidebarProxy,
    SkeletonContainer,
    StatusContainer,
    TabContainer,
    card,
    columns,
    container,
    expander,
    form,
    sidebar,
    skeleton,
    status,
    tabs,
)
from pyview.components.media import audio, image, logo, pdf, video
from pyview.components.status import (
    ProgressElement,
    SpinnerContext,
    balloons,
    divider,
    error,
    exception,
    info,
    metric,
    progress,
    snow,
    spinner,
    success,
    toast,
    warning,
)

__all__ = [
    # Base
    "Container",
    # Layout
    "columns",
    "ColumnContainer",
    "tabs",
    "TabContainer",
    "expander",
    "ExpanderContainer",
    "card",
    "CardContainer",
    "container",
    "form",
    "FormContainer",
    "status",
    "StatusContainer",
    "skeleton",
    "SkeletonContainer",
    "sidebar",
    "SidebarProxy",
    # Content
    "title",
    "header",
    "write",
    "json",
    # Inputs
    "button",
    "download_button",
    "link_button",
    "form_submit_button",
    "text_input",
    "text_area",
    "chat_input",
    "slider",
    "select_slider",
    "number_input",
    "selectbox",
    "multiselect",
    "radio",
    "segmented_control",
    "pills",
    "checkbox",
    "toggle",
    "date_input",
    "time_input",
    "color_picker",
    "file_uploader",
    "feedback",
    # Data
    "table",
    "dataframe",
    "data_editor",
    "Column",
    "TextColumn",
    "NumberColumn",
    "CheckboxColumn",
    "SelectboxColumn",
    "ProgressColumn",
    "LinkColumn",
    "normalize_tabular_data",
    "reconstruct_tabular_data",
    # Media
    "image",
    "audio",
    "video",
    "logo",
    "pdf",
    # Status
    "progress",
    "ProgressElement",
    "spinner",
    "SpinnerContext",
    "toast",
    "balloons",
    "snow",
    "exception",
    "success",
    "info",
    "warning",
    "error",
    "divider",
    "metric",
]
